version: "3.9"

services:
  mongodb:
    container_name: mongodb_service
    image: "mongo:latest"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      mynetwork:
        aliases:
          - mongodb-service

  redis:
    container_name: redis_service
    image: "redis:latest"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      mynetwork:
        aliases:
          - redis-service

  app:
    container_name: hello-wops
    build: 
       context: .
    depends_on:
      - mongodb
      - redis
    ports:
      - "3000:3000"
    environment:
      - MONGO_HOST=mongodb-service
      - MONGO_PORT=27017
      - REDIS_HOST=redis-service
      - REDIS_PORT=6379
      - PORT=3000
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
